### ISSUE TITLE
L.define works differently or does not work at all since version 3.6.1

### ISSUE THREAD

**Issue by minevala** [calmm-js/partial.lenses#30] opened 2016-05-31 13:41 UTC
Hello, 
we noticed that following expression P("related", L.define([])) returns undefined and for example P("related", L.defaults([])) returns [].

**Comment by polytypic** [comment] 2016-05-31 14:02
Ouch!  Yes, that is a bug.  Will fix ASAP.

**Comment by polytypic** [comment] 2016-05-31 14:10
Should be fixed now in 3.6.3 and is also tested against.  Thanks for reporting the bug and apologies for the inconvenience!

The bug was caused by forgetting to change the one internal use of `R.compose` after changing the internal implementation to allow for traversals.

**Closed by polytypic** 2016-05-31 14:10 UTC

**Comment by minevala** [comment] 2016-05-31 14:19
Thank you for the really fast fix 🙇  👍

**Comment by minevala** [comment] 2016-05-31 14:27
No worries, no harm done. Everything works now like a charm 👍

**Comment by polytypic** [comment] 2016-05-31 14:28
No problem.  Good to hear things are back in working order! :)
